#!/bin/bash

target_dir="/home/artifact/experiment-dir"
oldness_dir="/home/artifact/experiment-dir-oldness"
sizes_dir="/home/artifact/experiment-dir-sizes"

cd ~/Desktop/pacsolve/slurm/

mkdir -p "$oldness_dir"
mkdir -p "$sizes_dir"

# Prepare oldness analysis
python3 all_oldness.py "$target_dir"/vanilla > "$oldness_dir"/vanilla.csv
python3 all_oldness.py "$target_dir"/rosette/npm/allow_cycles/min_oldness,min_num_deps > "$oldness_dir"/rosette-npm-allow_cycles-min_oldness-min_num_deps.csv
python3 all_oldness.py "$target_dir"/rosette/npm/allow_cycles/min_num_deps,min_oldness > "$oldness_dir"/rosette-npm-allow_cycles-min_num_deps-min_oldness.csv

# Prepare size analysis
./get_file_sizes "$target_dir"/vanilla > "$sizes_dir"/vanilla.tsv
./get_file_sizes "$target_dir"/rosette/npm/allow_cycles/min_num_deps,min_oldness > "$sizes_dir"/npm_min_num_deps.tsv
./get_file_sizes "$target_dir"/rosette/npm/allow_cycles/min_oldness,min_num_deps > "$sizes_dir"/npm_min_oldness.tsv
./get_file_sizes "$target_dir"/rosette/npm/allow_cycles/min_duplicates,min_oldness > "$sizes_dir"/npm_min_duplicates.tsv

Rscript get_analysis_script.R
