#!/bin/bash
set -e

target_dir="/home/artifact/experiment-dir"
perf_dir="/home/artifact/experiment-dir-perf"

mkdir -p $perf_dir

cd /home/artifact/pacsolve/slurm/
./performance.py --target "$target_dir"/vanilla/no > "$perf_dir"/vanilla-perf.csv
./performance.py --target "$target_dir"/rosette/npm/allow_cycles/min_cve,min_oldness > "$perf_dir"/rosette-perf.csv
