#!/bin/bash
set -e

target_dir="/home/artifact/experiment-dir"
perf_dir="/home/artifact/experiment-dir-perf"

cd ~/Desktop/pacsolve/slurm/
./performance.py --target "$target_dir"/vanilla > "$perf_dir"/vanilla-perf.csv
./performance.py --target "$target_dir"/rosette/npm/allow_cycles/min_oldness,min_num_deps > "$perf_dir"/rosette-perf.csv